### ISSUE TITLE
Question: aren't notes supposed to belong to a pet?

### ISSUE THREAD

**Issue by median-man** [elenaliu0415/healthy-pets#27]
Correct me if I'm mistaken, but didn't we determine that notes belonged to pets?

https://github.com/elenaliu0415/healthy-pets/blob/9008340ce2fa432e7c987ae3ba73ef95ab21beac/server/schemas/typeDefs.js#L16

**Comment by Ivo-Gatzinski** [comment]
Yes, we need to move this to pets in typeDefs!
